;;; clime-skill-tests.el --- Tests for clime-skill  -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;; This file is not part of GNU Emacs.

;;; Commentary:

;; Tests for the provider-neutral Agent Skill exporter.  Cover three
;; layers: projection (clime-app tree -> manifest), rendering (manifest
;; -> canonical SKILL.md), and writing/targets (atomic directory write,
;; portable/Codex/Claude layouts, overwrite policy).
;;
;; Security is a first-class concern: sentinel secret values are placed
;; in the environment, in a function-valued default, and behind a
;; function-valued :choices; every test proves those secrets never reach
;; a generated byte and that no handler / choices function is executed.

;;; Code:

(require 'ert)
(require 'clime-core)
(require 'clime-dsl)
(require 'clime-run)
(require 'clime-skill)
(require 'clime-make)
(require 'clime-test-helpers)

;;; ─── Sentinels ─────────────────────────────────────────────────────────

(defconst clime-skill-test--secret "SENTINEL-SECRET-DO-NOT-LEAK-9f3a2b7c"
  "A value that must never appear in any generated skill byte.")

(defvar clime-skill-test--handler-ran nil
  "Set to t by a fixture handler; must stay nil during export.")

(defvar clime-skill-test--choices-called nil
  "Set to t by a fixture :choices function; must stay nil during export.")

(defun clime-skill-test--secret-default ()
  "A lazy default that would leak the secret if resolved."
  (setq clime-skill-test--handler-ran 'default-called)
  clime-skill-test--secret)

(defun clime-skill-test--secret-choices ()
  "A dynamic :choices function that would leak the secret if called."
  (setq clime-skill-test--choices-called t)
  (list clime-skill-test--secret "safe-mode"))

;;; ─── Fixtures ──────────────────────────────────────────────────────────

(defun clime-skill-test--build-app ()
  "Build a rich fixture app exercising the projected metadata surface."
  (clime-app demo-cli
    :version "1.2.3"
    :env-prefix "DEMO"
    :help "Demo CLI for skill export tests.\nSecond line must not enter the description."
    :examples '("demo greet alice --shout" "demo db migrate 3")
    (clime-opt verbose ("--verbose" "-v") :count :help "Increase verbosity")
    (clime-opt token ("--token") :env t :help "API token")
    (clime-command greet
      :help "Greet someone by name"
      (clime-arg name :help "Who to greet" :choices '("alice" "bob"))
      (clime-opt shout ("--shout" "-s") :bool :help "Uppercase the greeting")
      (clime-opt lang ("--lang" "-l") :default "en" :choices '("en" "fr")
        :help "Language")
      (clime-handler (ctx)
        (ignore ctx) (setq clime-skill-test--handler-ran t) ""))
    (clime-group db
      :help "Database operations"
      (clime-opt dsn ("--dsn") :help "Data source name")
      (clime-command migrate
        :help "Run migrations"
        (clime-arg steps :type 'integer :required nil :default 1
          :help "How many steps")
        (clime-arg files :nargs :rest :required nil :help "Extra files")
        (clime-opt secret ("--secret")
          :default #'clime-skill-test--secret-default :help "Secret option")
        (clime-opt mode ("--mode")
          :choices #'clime-skill-test--secret-choices :help "Mode")
        (clime-opt tags ("--tag" "-t") :multiple :help "Repeatable tag")
        (clime-opt point ("--point") :nargs 2 :help "A coordinate pair")
        (clime-handler (ctx)
          (ignore ctx) (setq clime-skill-test--handler-ran t) "")))))

(defmacro clime-skill-test--with-fixture (var &rest body)
  "Bind VAR to a fresh fixture app and reset sentinels for BODY.
Sets DEMO_TOKEN in the environment to the secret so tests prove the
env *value* never leaks (only its name is a legitimate contract)."
  (declare (indent 1) (debug t))
  `(let ((clime-skill-test--handler-ran nil)
         (clime-skill-test--choices-called nil)
         (process-environment
          (cons (concat "DEMO_TOKEN=" clime-skill-test--secret)
                process-environment))
         (,var (clime-skill-test--build-app)))
     ,@body))

(defun clime-skill-test--node (manifest &rest path)
  "Return the node in MANIFEST reached by PATH segments (strings)."
  (let ((node (plist-get manifest :root)))
    (dolist (seg path node)
      (setq node (cl-find seg (plist-get node :commands)
                          :key (lambda (n) (plist-get n :name))
                          :test #'equal)))))

(defun clime-skill-test--opt (node flag)
  "Return the option entry in NODE whose :flags contains FLAG."
  (cl-find-if (lambda (o) (member flag (plist-get o :flags)))
              (plist-get node :options)))

(defun clime-skill-test--arg (node name)
  "Return the argument entry named NAME in NODE."
  (cl-find name (plist-get node :arguments)
           :key (lambda (a) (plist-get a :name)) :test #'equal))

(defun clime-skill-test--parse-frontmatter (str)
  "Parse the leading YAML frontmatter block of STR into an alist.
Returns (KEY . VALUE) string pairs from the `---'-delimited header."
  (unless (string-prefix-p "---\n" str)
    (error "no frontmatter delimiter"))
  (let* ((rest (substring str 4))
         (end (string-match "\n---\n" rest)))
    (unless end (error "unterminated frontmatter"))
    (let ((block (substring rest 0 end))
          (alist nil))
      (dolist (line (split-string block "\n" t) (nreverse alist))
        (when (string-match "\\`\\([A-Za-z0-9_-]+\\): ?\\(.*\\)\\'" line)
          (push (cons (match-string 1 line) (match-string 2 line)) alist))))))

;;; ─── Projection ────────────────────────────────────────────────────────

(ert-deftest clime-test-skill/manifest-header ()
  "Manifest carries name, command spelling, version, and description."
  (clime-skill-test--with-fixture app
    (let ((m (clime-skill-manifest app :command "demo")))
      (should (equal (plist-get m :command) "demo"))
      (should (equal (plist-get m :version) "1.2.3"))
      ;; description is the FIRST line of help only
      (should (equal (plist-get m :description)
                     "Demo CLI for skill export tests."))
      (should (equal (plist-get m :name) "demo-cli")))))

(ert-deftest clime-test-skill/manifest-nested-paths ()
  "Manifest mirrors nested command paths in declaration order."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (root (plist-get m :root))
           (names (mapcar (lambda (n) (plist-get n :name))
                          (plist-get root :commands))))
      (should (equal names '("greet" "db")))
      (should (equal (plist-get (clime-skill-test--node m "greet") :path)
                     '("greet")))
      (should (equal (plist-get (clime-skill-test--node m "db" "migrate") :path)
                     '("db" "migrate")))
      (should (equal (plist-get (clime-skill-test--node m "db" "migrate") :kind)
                     'command))
      (should (equal (plist-get (clime-skill-test--node m "db") :kind) 'group)))))

(ert-deftest clime-test-skill/manifest-option-metadata ()
  "Option flags/aliases, requiredness, multiplicity, choices, default."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (greet (clime-skill-test--node m "greet"))
           (shout (clime-skill-test--opt greet "--shout"))
           (lang (clime-skill-test--opt greet "--lang"))
           (root (plist-get m :root))
           (verbose (clime-skill-test--opt root "--verbose"))
           (migrate (clime-skill-test--node m "db" "migrate"))
           (tags (clime-skill-test--opt migrate "--tag")))
      ;; boolean
      (should (plist-get shout :boolean))
      (should (member "-s" (plist-get shout :flags)))
      ;; count is boolean-like and keeps both aliases
      (should (plist-get verbose :boolean))
      (should (equal (plist-get verbose :flags) '("-v" "--verbose")))
      ;; literal choices + safe literal default
      (should (equal (plist-get lang :choices) '("en" "fr")))
      (should (equal (plist-get lang :default) "en"))
      (should-not (plist-get lang :boolean))
      ;; repeatable
      (should (plist-get tags :multiple)))))

(ert-deftest clime-test-skill/manifest-arg-metadata ()
  "Positional args carry required/nargs/rest/type/choices."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (greet (clime-skill-test--node m "greet"))
           (name (clime-skill-test--arg greet "name"))
           (migrate (clime-skill-test--node m "db" "migrate"))
           (steps (clime-skill-test--arg migrate "steps"))
           (files (clime-skill-test--arg migrate "files")))
      (should (plist-get name :required))
      (should (equal (plist-get name :choices) '("alice" "bob")))
      (should-not (plist-get steps :required))
      (should (equal (plist-get steps :default) 1))
      (should (equal (plist-get steps :type) "integer"))
      (should (equal (plist-get files :nargs) :rest)))))

(ert-deftest clime-test-skill/manifest-env-name-only ()
  "Env option carries the derived NAME, never the resolved value."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (root (plist-get m :root))
           (token (clime-skill-test--opt root "--token")))
      (should (equal (plist-get token :env) "DEMO_TOKEN"))
      ;; the environment value is the secret; it must not be captured
      (should-not (string-match-p clime-skill-test--secret
                                  (format "%S" m))))))

(ert-deftest clime-test-skill/manifest-function-default-omitted ()
  "A function-valued default is omitted and never called."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (migrate (clime-skill-test--node m "db" "migrate"))
           (secret (clime-skill-test--opt migrate "--secret")))
      (should-not (plist-member secret :default))
      (should (null clime-skill-test--handler-ran))
      (should-not (string-match-p clime-skill-test--secret (format "%S" m))))))

(ert-deftest clime-test-skill/manifest-dynamic-choices-not-called ()
  "A function-valued :choices is marked dynamic and never invoked."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (migrate (clime-skill-test--node m "db" "migrate"))
           (mode (clime-skill-test--opt migrate "--mode")))
      (should (null clime-skill-test--choices-called))
      (should (eq (plist-get mode :choices) 'runtime))
      (should-not (string-match-p clime-skill-test--secret (format "%S" m))))))

;;; ─── Rendering ─────────────────────────────────────────────────────────

(ert-deftest clime-test-skill/render-frontmatter ()
  "Rendered SKILL.md opens with parseable name+description frontmatter."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m))
           (fm (clime-skill-test--parse-frontmatter out)))
      (should (equal (cdr (assoc "name" fm)) "demo-cli"))
      (should (equal (cdr (assoc "description" fm))
                     "Demo CLI for skill export tests.")))))

(ert-deftest clime-test-skill/render-deterministic ()
  "Rendering the same manifest twice is byte-identical."
  (clime-skill-test--with-fixture app
    (let ((m (clime-skill-manifest app :command "demo")))
      (should (equal (clime-skill-render m) (clime-skill-render m))))))

(ert-deftest clime-test-skill/render-covers-contract ()
  "Rendered text names command paths, flags, and end-of-options."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m)))
      (should (string-match-p "demo greet" out))
      (should (string-match-p "demo db migrate" out))
      (should (string-match-p "--shout" out))
      (should (string-match-p "--verbose" out))
      ;; end-of-options behavior is documented
      (should (string-match-p "`--`" out))
      ;; nested arg with rest and choices surfaced
      (should (string-match-p "alice" out)))))

(ert-deftest clime-test-skill/render-secret-absent ()
  "No sentinel secret survives into the rendered document."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m)))
      (should-not (string-match-p clime-skill-test--secret out))
      (should (null clime-skill-test--handler-ran))
      (should (null clime-skill-test--choices-called)))))

;;; ─── Writing / targets ─────────────────────────────────────────────────

(ert-deftest clime-test-skill/write-portable ()
  "Portable target writes SKILL.md into the given output directory."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((dir (expand-file-name "out" temp-dir))
             (m (clime-skill-manifest app :command "demo"))
             (dest (clime-skill-write m :target 'portable :output dir))
             (skill (expand-file-name "SKILL.md" dest)))
        (should (file-directory-p dest))
        (should (file-exists-p skill))
        (with-temp-buffer
          (insert-file-contents skill)
          (should (clime-skill-test--parse-frontmatter (buffer-string))))))))

(ert-deftest clime-test-skill/write-codex-layout ()
  "Codex target installs under .agents/skills/NAME/."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((m (clime-skill-manifest app :command "demo"))
             (dest (clime-skill-write m :target 'codex :output temp-dir)))
        (should (file-exists-p
                 (expand-file-name ".agents/skills/demo-cli/SKILL.md" temp-dir)))
        (should (equal (file-name-nondirectory (directory-file-name dest))
                       "demo-cli"))))))

(ert-deftest clime-test-skill/write-claude-layout ()
  "Claude target installs under .claude/skills/NAME/."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let ((m (clime-skill-manifest app :command "demo")))
        (clime-skill-write m :target 'claude :output temp-dir)
        (should (file-exists-p
                 (expand-file-name ".claude/skills/demo-cli/SKILL.md"
                                   temp-dir)))))))

(ert-deftest clime-test-skill/write-targets-semantically-equal ()
  "Codex and Claude layouts render the same SKILL.md contents."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((m (clime-skill-manifest app :command "demo"))
             (base-a (expand-file-name "a" temp-dir))
             (base-b (expand-file-name "b" temp-dir)))
        (make-directory base-a) (make-directory base-b)
        (clime-skill-write m :target 'codex :output base-a)
        (clime-skill-write m :target 'claude :output base-b)
        (let ((codex (expand-file-name ".agents/skills/demo-cli/SKILL.md" base-a))
              (claude (expand-file-name ".claude/skills/demo-cli/SKILL.md" base-b)))
          (should (equal (with-temp-buffer (insert-file-contents codex)
                                           (buffer-string))
                         (with-temp-buffer (insert-file-contents claude)
                                           (buffer-string)))))))))

(ert-deftest clime-test-skill/write-force-policy ()
  "Existing destination fails closed unless :force is supplied."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((dir (expand-file-name "out" temp-dir))
             (m (clime-skill-manifest app :command "demo")))
        (clime-skill-write m :target 'portable :output dir)
        ;; second write without force must error and preserve the marker
        (write-region "keep" nil (expand-file-name "marker" dir))
        (should-error (clime-skill-write m :target 'portable :output dir))
        (should (file-exists-p (expand-file-name "marker" dir)))
        ;; with force it replaces the directory (marker gone)
        (clime-skill-write m :target 'portable :output dir :force t)
        (should (file-exists-p (expand-file-name "SKILL.md" dir)))
        (should-not (file-exists-p (expand-file-name "marker" dir)))))))

(ert-deftest clime-test-skill/write-byte-stable ()
  "Regenerating the same-named skill produces byte-identical files.
Uses the same directory basename under different parents: the rendered
`name' tracks the destination basename (Agent Skills conformance), so
determinism is checked with the name held constant."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((m (clime-skill-manifest app :command "demo"))
             (a (expand-file-name "p1/demo-cli" temp-dir))
             (b (expand-file-name "p2/demo-cli" temp-dir)))
        (clime-skill-write m :target 'portable :output a)
        (clime-skill-write m :target 'portable :output b)
        (should (equal (with-temp-buffer
                         (insert-file-contents (expand-file-name "SKILL.md" a))
                         (buffer-string))
                       (with-temp-buffer
                         (insert-file-contents (expand-file-name "SKILL.md" b))
                         (buffer-string))))))))

(ert-deftest clime-test-skill/write-atomic-no-partial ()
  "A failure during the final move leaves no destination directory."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((dir (expand-file-name "out" temp-dir))
             (m (clime-skill-manifest app :command "demo")))
        (cl-letf (((symbol-function 'rename-file)
                   (lambda (&rest _) (error "boom"))))
          (should-error (clime-skill-write m :target 'portable :output dir)))
        ;; no partial destination, no leftover temp dirs in the parent
        (should-not (file-exists-p dir))
        (should-not (cl-find-if
                     (lambda (f) (string-prefix-p "clime-skill" f))
                     (directory-files temp-dir)))))))

(ert-deftest clime-test-skill/export-runs-no-handler ()
  "Full export never executes a handler, default, or choices function."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let ((dir (expand-file-name "out" temp-dir)))
        (clime-skill-export app :command "demo" :target 'portable :output dir)
        (should (null clime-skill-test--handler-ran))
        (should (null clime-skill-test--choices-called))
        (with-temp-buffer
          (insert-file-contents (expand-file-name "SKILL.md" dir))
          (should-not (string-match-p clime-skill-test--secret
                                      (buffer-string))))))))

;;; ─── Blocker 1: Agent Skills conformance ───────────────────────────────

(ert-deftest clime-test-skill/name-length-bounded ()
  "A sanitized name is clamped to the 1–64 char Agent Skills bound."
  ;; 100 raw chars must not yield an over-length directory/name token.
  (let* ((raw (make-string 100 ?A))
         (name (clime-skill--sanitize-name raw)))
    (should (<= (length name) 64))
    (should (>= (length name) 1))
    ;; still a well-formed token: lowercase, no leading/trailing hyphen
    (should (string-match-p "\\`[a-z0-9]\\(?:[a-z0-9-]*[a-z0-9]\\)?\\'" name)))
  ;; hyphenation must not leave a trailing hyphen after truncation
  (let ((name (clime-skill--sanitize-name
               (concat (make-string 63 ?a) "----tail"))))
    (should (<= (length name) 64))
    (should-not (string-suffix-p "-" name))))

(ert-deftest clime-test-skill/description-fallback-when-empty ()
  "A nil/blank app help yields a non-empty, trigger-capable description."
  (let* ((app (clime-app nohelp-cli
                (clime-command work (clime-handler (ctx) (ignore ctx) ""))))
         (m (clime-skill-manifest app :command "toolx"))
         (desc (plist-get m :description)))
    (should (stringp desc))
    (should (> (length desc) 0))
    (should (<= (length desc) 1024))
    ;; trigger-capable: names the command so an agent knows when it applies
    (should (string-match-p "toolx" desc))))

(ert-deftest clime-test-skill/description-length-bounded ()
  "An over-long help first line is clamped to the 1024 char bound."
  (let* ((long (make-string 4000 ?x))
         (app (clime-app big-cli
                :help long
                (clime-command work (clime-handler (ctx) (ignore ctx) ""))))
         (m (clime-skill-manifest app :command "big"))
         (desc (plist-get m :description)))
    (should (<= (length desc) 1024))
    (should (> (length desc) 0))))

(ert-deftest clime-test-skill/yaml-scalar-type-safe ()
  "Type-ambiguous scalars are quoted so YAML keeps them as strings."
  ;; booleans, null, and numbers must never be emitted as bare scalars
  (dolist (s '("true" "false" "yes" "no" "on" "off" "null"
               "True" "YES" "Off" "123" "3.14" "-5" "0" "y" "N"))
    (let ((out (clime-skill--yaml-scalar s)))
      (should (string-prefix-p "\"" out))
      (should (string-suffix-p "\"" out))))
  ;; ordinary prose stays plain (no needless quoting)
  (should (equal (clime-skill--yaml-scalar "Manage widgets") "Manage widgets"))
  ;; structural characters still force quoting
  (should (string-prefix-p "\"" (clime-skill--yaml-scalar "a: b")))
  (should (string-prefix-p "\"" (clime-skill--yaml-scalar "# c"))))

(ert-deftest clime-test-skill/frontmatter-conformance ()
  "Rendered frontmatter conforms: name token + string-typed description."
  (let* ((app (clime-app conf-cli
                :help "true"            ; ambiguous: must render quoted
                (clime-command work (clime-handler (ctx) (ignore ctx) ""))))
         (m (clime-skill-manifest app :command "conf"))
         (out (clime-skill-render m))
         (fm (clime-skill-test--parse-frontmatter out))
         (name (cdr (assoc "name" fm)))
         (desc (cdr (assoc "description" fm))))
    ;; name: 1–64, directory-safe token
    (should (string-match-p "\\`[a-z0-9]\\(?:[a-z0-9-]*[a-z0-9]\\)?\\'" name))
    (should (<= (length name) 64))
    ;; description scalar is quoted (would otherwise parse as YAML boolean)
    (should (string-prefix-p "\"" desc))))

;;; ─── Blocker 2: exact Clime invocation grammar ─────────────────────────

(ert-deftest clime-test-skill/render-fixed-nargs-option ()
  "A fixed nargs=N option renders N distinct value placeholders."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m)))
      (should (string-match-p "--point <value> <value>" out)))))

(ert-deftest clime-test-skill/render-fixed-nargs-arg ()
  "A fixed nargs=N positional renders N distinct placeholders."
  ;; Hand-built manifest exercises arg-level fixed nargs directly.
  (let* ((manifest
          (list :name "demo" :command "demo" :version nil :description "D"
                :root (list :kind 'app :name "demo" :path nil :help nil
                            :arguments nil :options nil
                            :commands
                            (list (list :kind 'command :name "move"
                                        :path '("move") :help "Move"
                                        :options nil
                                        :arguments
                                        (list (list :name "coords" :required t
                                                    :nargs 2)))))))
         (out (clime-skill-render manifest)))
    (should (string-match-p "<coords> <coords>" out))))

(ert-deftest clime-test-skill/render-count-repeatable ()
  "A :count option is documented as repeatable/accumulating."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m)))
      ;; the verbose line must convey accumulation, not a plain flag
      (should (string-match-p "--verbose" out))
      (should (string-match-p "accumulat" out)))))

(ert-deftest clime-test-skill/render-root-examples ()
  "Root (app-level) declared examples appear in the rendered document."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m)))
      (should (string-match-p "demo greet alice --shout" out)))))

(ert-deftest clime-test-skill/render-root-args ()
  "Root (app-level) positional arguments are rendered."
  (let* ((app (clime-app rooted-cli
                :help "Root with a positional"
                (clime-arg target :required t :help "The target")
                (clime-handler (ctx) (ignore ctx) "")))
         (m (clime-skill-manifest app :command "rooted"))
         (out (clime-skill-render m)))
    (should (string-match-p "<target>" out))))

(ert-deftest clime-test-skill/render-group-scope-ordering ()
  "Usage documents option scope: root global, subcommand options follow."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m)))
      ;; root/global options are documented as global until `--'
      (should (string-match-p "global" out))
      ;; and the per-node scope rule is stated
      (should (string-match-p "belong to" out)))))

;;; ─── Blocker 3: rollback-safe forced replacement ───────────────────────

(ert-deftest clime-test-skill/write-force-rollback-preserves-old ()
  "A rename failure mid-force-replace restores the previous skill."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((dir (expand-file-name "out" temp-dir))
             (m (clime-skill-manifest app :command "demo")))
        ;; install v1, then plant a marker that must survive a failed replace
        (clime-skill-write m :target 'portable :output dir)
        (write-region "OLD-CONTENT" nil (expand-file-name "marker" dir))
        ;; fail the *install* rename (2nd rename), not the move-aside (1st)
        (let* ((orig (symbol-function 'rename-file))
               (n 0))
          (cl-letf (((symbol-function 'rename-file)
                     (lambda (a b &optional ok-if-exists)
                       (cl-incf n)
                       (if (= n 2)
                           (error "boom during install")
                         (funcall orig a b ok-if-exists)))))
            (should-error
             (clime-skill-write m :target 'portable :output dir :force t))))
        ;; the previous skill (and its marker) must be intact — not lost
        (should (file-directory-p dir))
        (should (file-exists-p (expand-file-name "marker" dir)))
        (should (equal "OLD-CONTENT"
                       (with-temp-buffer
                         (insert-file-contents (expand-file-name "marker" dir))
                         (buffer-string))))
        ;; no backup/temp scaffolding left behind
        (should-not (cl-find-if
                     (lambda (f) (string-prefix-p "clime-skill" f))
                     (directory-files temp-dir)))))))

;;; ─── Blocker 4: safe command spelling ──────────────────────────────────

(ert-deftest clime-test-skill/command-spelling-rejects-metacharacters ()
  "Shell/Markdown metacharacters in a command spelling are rejected."
  (clime-skill-test--with-fixture app
    (dolist (bad '("demo; rm -rf /"
                   "demo`whoami`"
                   "demo$(id)"
                   "demo && echo x"
                   "demo | tee out"
                   "demo > /etc/passwd"
                   "demo\nrm"
                   "de mo"
                   "$(evil)"
                   "demo\"x"
                   "-rf"))
      (should-error (clime-skill-manifest app :command bad)
                    :type 'clime-usage-error))))

(ert-deftest clime-test-skill/command-spelling-accepts-safe-tokens ()
  "Plain executable tokens (incl. path forms) are accepted verbatim."
  (clime-skill-test--with-fixture app
    (dolist (ok '("demo" "clime-make" "bin/clime" "./clime"
                  "/usr/bin/clime" "demo.el" "demo_v2"))
      (let ((m (clime-skill-manifest app :command ok)))
        (should (equal (plist-get m :command) ok))))))

;;; ─── nav-contract REFINE findings (2026-08-28) ─────────────────────────

;; Finding 1 — Agent Skills name/directory conformance for portable output.

(ert-deftest clime-test-skill/write-portable-name-matches-directory ()
  "Portable output: rendered `name' equals the destination dir basename.
The app is named demo-cli but is written to a `my-skill' directory; the
spec requires name to match the directory, so it must be `my-skill'."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((dir (expand-file-name "my-skill" temp-dir))
             (m (clime-skill-manifest app :command "demo")))
        (should (equal (plist-get m :name) "demo-cli")) ; premise: differs
        (clime-skill-write m :target 'portable :output dir)
        (let ((fm (with-temp-buffer
                    (insert-file-contents (expand-file-name "SKILL.md" dir))
                    (clime-skill-test--parse-frontmatter (buffer-string)))))
          (should (equal (cdr (assoc "name" fm)) "my-skill"))
          (should-not (equal (cdr (assoc "name" fm)) "demo-cli")))))))

(ert-deftest clime-test-skill/write-portable-rejects-nonconformant-dir ()
  "A portable output whose basename is not a valid skill name errors.
Prevents emitting a `name' that cannot equal a non-conformant directory."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let ((m (clime-skill-manifest app :command "demo")))
        (dolist (bad '("Bad_Name" "UPPER" "has space" "trailing-"))
          (should-error
           (clime-skill-write m :target 'portable
                              :output (expand-file-name bad temp-dir))
           :type 'clime-usage-error))))))

(ert-deftest clime-test-skill/write-codex-name-matches-directory ()
  "Codex/Claude: rendered `name' equals the skills/NAME dir basename.
Regression guard — these layouts build the directory from the name, so
they already agree; assert it explicitly."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let ((m (clime-skill-manifest app :command "demo")))
        (clime-skill-write m :target 'codex :output temp-dir)
        (let ((fm (with-temp-buffer
                    (insert-file-contents
                     (expand-file-name ".agents/skills/demo-cli/SKILL.md"
                                       temp-dir))
                    (clime-skill-test--parse-frontmatter (buffer-string)))))
          (should (equal (cdr (assoc "name" fm)) "demo-cli")))))))

;; Finding 2 — exact :multiple space-separated grammar.

(ert-deftest clime-test-skill/render-multiple-space-separated ()
  "A :multiple option documents both repeated and space-separated values.
Clime accepts `--tag a b c' where unambiguous, not just repetition."
  (clime-skill-test--with-fixture app
    (let* ((m (clime-skill-manifest app :command "demo"))
           (out (clime-skill-render m)))
      ;; grammar must name the space-separated form, not only 'repeatable'
      (should (string-match-p "space-separated" out))
      (should (string-match-p "a b c" out)))))

;; Finding 3 — forced replacement preserves the backup when the restore
;; rename ALSO fails (double failure), rather than deleting it.

(ert-deftest clime-test-skill/write-force-rollback-double-failure-preserves-backup ()
  "When BOTH install and restore renames fail, the old skill survives.
The previous bytes must remain recoverable in a preserved backup, never
deleted by cleanup."
  (clime-skill-test--with-fixture app
    (clime-test-with-temp-dir
      (let* ((dir (expand-file-name "out" temp-dir))
             (m (clime-skill-manifest app :command "demo")))
        (clime-skill-write m :target 'portable :output dir)
        (write-region "OLD-CONTENT" nil (expand-file-name "marker" dir))
        ;; move-aside (rename #1) succeeds; install (#2) and restore (#3) fail
        (let* ((orig (symbol-function 'rename-file))
               (n 0))
          (cl-letf (((symbol-function 'rename-file)
                     (lambda (a b &optional ok-if-exists)
                       (cl-incf n)
                       (if (>= n 2)
                           (error "boom rename %d" n)
                         (funcall orig a b ok-if-exists)))))
            (should-error
             (clime-skill-write m :target 'portable :output dir :force t))))
        ;; the old marker bytes must survive in a preserved backup directory
        (let ((survivor
               (cl-find-if
                (lambda (d)
                  (and (file-directory-p d)
                       (let ((mk (expand-file-name "marker" d)))
                         (and (file-exists-p mk)
                              (equal "OLD-CONTENT"
                                     (with-temp-buffer
                                       (insert-file-contents mk)
                                       (buffer-string)))))))
                (directory-files temp-dir t "clime-skill-bak"))))
          (should survivor))))))

;;; ─── Integration via `clime-make skill' ────────────────────────────────

(defconst clime-skill-test--app-source "\
(require 'clime)
(defvar demo-integ--choices-called nil)
(defun demo-integ--secret-default () \"SENTINEL-SECRET-DO-NOT-LEAK-9f3a2b7c\")
(defun demo-integ--secret-choices ()
  (setq demo-integ--choices-called t)
  (list \"SENTINEL-SECRET-DO-NOT-LEAK-9f3a2b7c\" \"safe\"))
(clime-app demo-cli
  :version \"1.2.3\"
  :env-prefix \"DEMO\"
  :help \"Demo CLI for skill export tests.\"
  (clime-opt token (\"--token\") :env t :help \"API token\")
  (clime-command greet
    :help \"Greet someone\"
    (clime-arg name :help \"Who\" :choices '(\"alice\" \"bob\"))
    (clime-opt shout (\"--shout\" \"-s\") :bool :help \"Uppercase\")
    (clime-handler (ctx) (ignore ctx) \"\"))
  (clime-group db
    :help \"Database ops\"
    (clime-command migrate
      :help \"Run migrations\"
      (clime-arg steps :type 'integer :required nil :default 1 :help \"Steps\")
      (clime-opt secret (\"--secret\") :default #'demo-integ--secret-default
        :help \"Secret\")
      (clime-opt mode (\"--mode\") :choices #'demo-integ--secret-choices
        :help \"Mode\")
      (clime-handler (ctx) (ignore ctx) \"\"))))
(provide 'demo-cli)
"
  "Self-contained fixture app source written to a temp file.")

(defun clime-skill-test--run-make (&rest argv)
  "Run the clime-make app with ARGV, returning the exit code.
Output is captured so the batch test stays quiet."
  (let ((exit nil))
    (with-temp-buffer
      (let ((standard-output (current-buffer)))
        (setq exit (clime-run clime-make argv))))
    exit))

(defmacro clime-skill-test--with-app-file (file &rest body)
  "Write the fixture source to FILE inside a temp dir for BODY."
  (declare (indent 1) (debug t))
  `(clime-test-with-temp-dir
     (let ((,file (expand-file-name "demo-cli.el" temp-dir))
           (process-environment
            (cons (concat "DEMO_TOKEN=" clime-skill-test--secret)
                  process-environment)))
       (with-temp-file ,file
         (insert clime-skill-test--app-source))
       ,@body)))

(ert-deftest clime-test-skill/cli-portable ()
  "`clime-make skill FILE --command C --output DIR' builds a skill dir."
  (clime-skill-test--with-app-file file
    (let* ((out (expand-file-name "gen" temp-dir))
           (code (clime-skill-test--run-make
                  "skill" file "--command" "demo" "--output" out)))
      (should (= code 0))
      (should (file-exists-p (expand-file-name "SKILL.md" out)))
      (with-temp-buffer
        (insert-file-contents (expand-file-name "SKILL.md" out))
        (should (clime-skill-test--parse-frontmatter (buffer-string)))
        (should-not (string-match-p clime-skill-test--secret
                                    (buffer-string)))))))

(ert-deftest clime-test-skill/cli-codex ()
  "`--target codex' installs under .agents/skills/NAME/."
  (clime-skill-test--with-app-file file
    (let ((code (clime-skill-test--run-make
                 "skill" file "--command" "demo"
                 "--target" "codex" "--output" temp-dir)))
      (should (= code 0))
      (should (file-exists-p
               (expand-file-name ".agents/skills/demo-cli/SKILL.md" temp-dir))))))

(ert-deftest clime-test-skill/cli-claude ()
  "`--target claude' installs under .claude/skills/NAME/."
  (clime-skill-test--with-app-file file
    (let ((code (clime-skill-test--run-make
                 "skill" file "--command" "demo"
                 "--target" "claude" "--output" temp-dir)))
      (should (= code 0))
      (should (file-exists-p
               (expand-file-name ".claude/skills/demo-cli/SKILL.md" temp-dir))))))

(ert-deftest clime-test-skill/cli-app-override ()
  "`--app' selects the app symbol, matching serve's loader contract."
  (clime-skill-test--with-app-file file
    (let ((code (clime-skill-test--run-make
                 "skill" file "--app" "demo-cli" "--command" "demo"
                 "--output" (expand-file-name "gen" temp-dir))))
      (should (= code 0))
      (should (file-exists-p
               (expand-file-name "gen/SKILL.md" temp-dir))))))

(ert-deftest clime-test-skill/cli-force ()
  "Regeneration onto an existing dir needs --force."
  (clime-skill-test--with-app-file file
    (let ((out (expand-file-name "gen" temp-dir)))
      (should (= 0 (clime-skill-test--run-make
                    "skill" file "--command" "demo" "--output" out)))
      ;; second run without --force fails (non-zero exit)
      (should-not (= 0 (clime-skill-test--run-make
                        "skill" file "--command" "demo" "--output" out)))
      ;; with --force it succeeds
      (should (= 0 (clime-skill-test--run-make
                    "skill" file "--command" "demo" "--output" out
                    "--force"))))))

(ert-deftest clime-test-skill/cli-secret-absent-all-files ()
  "No GENERATED file contains the sentinel secret.
Scans only the generated skill tree — the input source file legitimately
contains the sentinel and is not a generated artifact."
  (clime-skill-test--with-app-file file
    (should (= 0 (clime-skill-test--run-make
                  "skill" file "--command" "demo"
                  "--target" "claude" "--output" temp-dir)))
    ;; the dynamic :choices function must never have been invoked
    (should (null (bound-and-true-p demo-integ--choices-called)))
    (let* ((skills (expand-file-name ".claude/skills/demo-cli" temp-dir))
           (files (directory-files-recursively skills ".*")))
      (should files)
      (dolist (f files)
        (with-temp-buffer
          (insert-file-contents f)
          (should-not (string-match-p clime-skill-test--secret
                                      (buffer-string))))))))

(provide 'clime-skill-tests)
;;; clime-skill-tests.el ends here
